apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bookinfo-certs-letsencrypt
spec:
  commonName: 'bookinfo.cjmays.com'
  dnsNames:
    - 'bookinfo.cjmays.com'
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: acme-prod-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    rotationPolicy: Always
    size: 2048
  renewBefore: 720h0m0s
  secretName: bookinfo-certs-letsencrypt