kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: bookinfo-route
spec:
  host: bookinfo.cjmays.com
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  port:
    targetPort: http2
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None